/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_rrd_RRDJNI */

#ifndef _Included_gnu_rrd_RRDJNI
#define _Included_gnu_rrd_RRDJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gnu_rrd_RRDJNI
 * Method:    create
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gnu_rrd_RRDJNI_create
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     gnu_rrd_RRDJNI
 * Method:    update
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gnu_rrd_RRDJNI_update
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     gnu_rrd_RRDJNI
 * Method:    graph
 * Signature: ([Ljava/lang/String;)Lgnu/rrd/RRDGraph;
 */
JNIEXPORT jobject JNICALL Java_gnu_rrd_RRDJNI_graph
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     gnu_rrd_RRDJNI
 * Method:    dump
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gnu_rrd_RRDJNI_dump
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     gnu_rrd_RRDJNI
 * Method:    restore
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gnu_rrd_RRDJNI_restore
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     gnu_rrd_RRDJNI
 * Method:    last
 * Signature: ([Ljava/lang/String;)Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_gnu_rrd_RRDJNI_last
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     gnu_rrd_RRDJNI
 * Method:    info
 * Signature: ([Ljava/lang/String;)Ljava/util/Hashtable;
 */
JNIEXPORT jobject JNICALL Java_gnu_rrd_RRDJNI_info
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     gnu_rrd_RRDJNI
 * Method:    fetch
 * Signature: ([Ljava/lang/String;)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_gnu_rrd_RRDJNI_fetch
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     gnu_rrd_RRDJNI
 * Method:    tune
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gnu_rrd_RRDJNI_tune
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     gnu_rrd_RRDJNI
 * Method:    resize
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gnu_rrd_RRDJNI_resize
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
