ALL: subdirs

subdirs: 
	$(MAKE) -C rrd ALL

classes: 
	$(MAKE) -C rrd classes

headers: 
	$(MAKE) -C rrd headers

jni:
	$(MAKE) -C rrd jni

install:
	$(MAKE) -C rrd install

clean:
	$(MAKE) -C rrd clean
